module.exports = {
    color: {
        col1:'white',
        text1:'red',
        text2:'grey',
        text3:'black'
    },
    title:{
        title1:30,
        btntxt:20
    },
    btn1:{
        width:'80%',
        height:50,
        backgroundColor:'red',
        borderRadius:10,
        alignItems:'center',
        justifyContent:'center',
        elevation:10,
        color:'white',
        marginVertical:5,
    },
    hr80:{
        width:'80%',
        borderBottomColor:'#E0E0E0',
        borderBottomWidth:2,
        marginVertical:20
    },
    veg:{
        backgroundColor:'green',
        width:20,
        height:20,
        borderRadius:5
    },
    nonVeg: {
        backgroundColor:'red',
        width:20,
        height:20,
        borderRadius:5
    },
    btn2:{
        width:150,
        height:50,
        backgroundColor:'red',
        borderRadius:10,
        alignItems:'center',
        justifyContent:'center',
        elevation:10,
        color:'white',
        marginVertical:5,
        marginHorizontal:15
    },
}